### ISSUE TITLE
Is possible to use F# for logic and not compile all to JS?

### ISSUE THREAD

**Issue by mamcx** [fsprojects/fable-react_native-demo#6]
I'm interested in build a cross-platform app and maybe react is the way, but wish to use F#. With this demo, look like everything is compiled to JS. What if I just wanna react **only for the UI** but the rest to use F# (like acces to sqlite, web apis, etc).

**Comment by forki** [comment]
I have no idea how this could work. Sorry

**Comment by alfonsogarciacaro** [comment]
There's already a sample of this, because the entry file is a [pure JS file that calls the JS generated by Fable](https://github.com/fsprojects/fable-react_native-demo/blob/master/index.android.js#L3). You just need to extend this pure JS layer and import the code generated by Fable when needed.

**Comment by forki** [comment]
that is compiled to JS as well?! What am I missing?

**Comment by alfonsogarciacaro** [comment]
I may have misunderstood the question. If you don't want to use compiled-to-JS F# I guess you'll have to compile F# to native Android or iOS code with Xamarin and then [interact with that from React Native](https://facebook.github.io/react-native/docs/communication-ios.html), but that won't likely be an easy feat.

**Comment by forki** [comment]
Tbh I don't think that's a way we should go. Js ecosystem is even richer than .net  ;')

**Comment by mamcx** [comment]
@alfonsogarciacaro Yeah, I wanna is use F# libraries and code for the backend, not turn everything in JS. So I have imagined something like `Client.GetList` will call the F# code `Server.GetList` and the heavy lifting will be there.
